### ISSUE TITLE
CSS Rich Browsing Proposal

### ISSUE THREAD

**Issue by HongZheng** [WebKit/Speedometer#175]
Hi everyone,
We are from Intel and want to introduce a CSS effects/animations rich workload into Speedoemeter3. Design doc is at https://docs.google.com/document/d/19vK5G11Kc4xbvhpkkXDf5WXdFQWyiK_a0WRwTUcc9j4/
I copied the contents of the document here in case you don't have access to it.

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-1a418814-7fff-1bf5-350c-5f168531abdf"><h1 dir="ltr" style="line-height:1.295;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:24pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Objective</span></h1><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The objective of this proposal is to introduce a CSS effects/animations rich test case that can help browsers measure and improve CSS performance.</span></p><h1 dir="ltr" style="line-height:1.295;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:24pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Motivation</span></h1><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CSS is an essential component of modern web development that helps developers build a large number of appealing and engaging websites. When CSS enables fancy webpages, the performance of CSS becomes an important factor affecting user experience on the web. Some web benchmarks normally measure CSS/DOM operations and JS tasks together, making it hard to check CSS performance/impact alone. Therefore, we propose adding a CSS heavy test case into Speedometer3 to help browsers measure and improve CSS performance.</span></p><h1 dir="ltr" style="line-height:1.295;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:24pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Description</span></h1><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">By learning from some real-life scenarios, such as image switching and table updating in </span><a href="https://top10.netflix.com/tv" style="text-decoration:none;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#0563c1;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://top10.netflix.com/tv</span></a><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> and </span><a href="https://www.imdb.com/" style="text-decoration:none;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#0563c1;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://www.imdb.com/</span></a><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, this proposal simulates a food menu with 5 kinds of food. Each food category contains 100 choices, and the first one is recommended. The proposal can automatically switch the 5 kinds of food one by one through clicking food pictures on the top of the page by JS. In the real world, web developers generally use CSS effects/animations to make web pages more appealing and engaging to end users. The proposal also exercises many CSS property operations (referencing the statistics from </span><a href="https://chromestatus.com/" style="text-decoration:none;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#0563c1;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://chromestatus.com/</span></a><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">), such as transform animation, opacity/color setting, position/size adjustment etc. The web page of this proposal looks like the image below.</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:251px;height:192px;"><img src="https://github-production-user-asset-6210df.s3.amazonaws.com/5335914/240141511-0271eb0c-2de4-40a4-8744-46206d52f1d9.png" width="351" height="269" style="margin-left:0px;margin-top:0px;" /></span></span></p><h1 dir="ltr" style="line-height:1.295;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:24pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Measurement methodology</span></h1><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">For performance measurement, the proposal utilizes performance.mark API to mark CSS animation frame start in requestAnimationFrame callback, and mark frame completion in the callback of afterframe API (</span><a href="https://www.npmjs.com/package/afterframe" style="text-decoration:none;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#0563c1;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://www.npmjs.com/package/afterframe</span></a><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">). The image below shows how to measure frame duration in Chrome trace. The final score reported is the average duration to render a frame in milliseconds.</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><span style="border:none;display:inline-block;overflow:hidden;width:624px;height:197px;">
<img src="https://github.com/WebKit/Speedometer/assets/5335914/9540795d-c959-4487-9f20-b4f170fc0384” width="873" height="276" style="margin-left:0px;margin-top:0px;" /></span></span></p><br /><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Code can be reviewed at</span><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> </span><a href="https://github.com/intel-staging/Speedometer/tree/rich_css/resources/tentative/rich-css" style="text-decoration:none;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://github.com/intel-staging/Speedometer/tree/rich_css/resources/tentative/rich-css</span></a></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Note: The workload can be run by launching index.html from the rich-css folder. It is not integrated into the benchmark runner yet.&nbsp;</span></p><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">A live demo is available at </span><a href="https://hongzheng.github.io/" style="text-decoration:none;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://hongzheng.github.io/</span></a></p><br /><h1 dir="ltr" style="line-height:1.295;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:24pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Results</span></h1><p dir="ltr" style="line-height:1.295;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:11pt;font-family:Calibri,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Run the proposal 10 rounds in Chrome/Firefox/Safari on M2, choose the median of the average frame time as final result and calculate variance using Coefficient of variation (Standard deviation divided by the mean)&nbsp;</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

M2 (MacOS Ventura 13.3.1) | Score(ms) | CV (Coefficient of variation)
-- | -- | --
Chrome (112.0.5615.137) | 11.7845 | 2.25%
Firefox (112.0.2) | 6.709 | 2.05%
Safari (16.4) | 21.072 | 7.63%

</div></b>
</body>
</html>

**Comment by camillobruni** [comment]
- Are you measuring Score or Time? (Your table header might be a bit confusing :))
- I tend towards excluding CSS animation from speedometer, as we might introduce frame-rate-based measurements here
- Other CSS and composting properties do seem fine with me

**Comment by MayuraRam** [comment]
- Yes- Time and not Score ( will edit)
- This methodology aims to avoid a frame-rate based measurement while reflecting the performance of heavy CSS operations seen in common real world use cases. It could be a good addition to Speedometer 3, which aims to reflect real-world user experiences. It stays away from Pure CSS animation, which would be hard to measure in a real world scenario.

**Comment by bgrins** [comment]
> the proposal utilizes performance.mark API to mark CSS animation frame start in requestAnimationFrame callback, and mark frame completion in the callback of afterframe API (https://www.npmjs.com/package/afterframe). 

I'm not familiar with that library, but it looks like it's essentially stopping the timer after the next rAF is fired following the rAF callback which starts the timer?

This isn't currently possible within the Speedometer framework, since we don't have the ability to perform async steps (and most likely won't within the version 3 timeframe, though we are definitely interested in developing this ability so we can test things like Workers). So if this is a requirement for the test we should look at this test as a potential addition for a future version. Though I wonder if it's possible to build a test with this content using a similar pattern to the NewsSite in #167 - for example having content get appended or toggling classes etc in a sync step.

**Comment by rniwa** [comment]
Yeah, we don't support this kind of async workload at the moment. Deferring this to v4 seems like the right course of action here.

**Comment by HongZheng** [comment]
Thanks all for your great comments!

Yes, the measurement of whole set of CSS animation frames depends on the async step in SP driver, which seems won’t be ready until SP4. We are updating the workload to adopt the measurement similar as NewsSite case mentioned by Brian. This is quite good because initial frame is measured, in particular if with rAF based async measurement (#173). 

The workload thus reflects web runtime’s responsiveness to user actions, when facing CSS heavy and animation rich scenarios in real world like Netflix and Amazon etc. The animations we use are based on statistics from [chromestatus](https://chromestatus.com/metrics/css/animated), which mentioned that animations are utilized by more than 40% webpages.

Again, thanks for the comments and we’ll soon have a new update and welcome your further insights to it!

**Comment by HongZheng** [comment]
We have integrated CSS rich workload into SP3. You can review the code at [https://github.com/intel-staging/Speedometer/tree/rich_css](https://github.com/intel-staging/Speedometer/tree/rich_css)
A live demo at [https://hongzheng.github.io/sp3-rich_css/?suite=Rich-CSS#home](https://hongzheng.github.io/sp3-rich_css/?suite=Rich-CSS#home)

**Comment by MayuraRam** [comment]
From discussion during meeting on 06/07/2023 - Please review the workload above. Could we do a PR and add the test to tentative?

**Comment by MayuraRam** [comment]
[From Hong Sheng] Thanks for the great and valuable comments!  Yes, it’s better to be changed to something like “Interacting with Featured Page to Navigate or Search Items” as suggested. We’re also considering to remove CSS gradient and blur from the implementation as well and replace with something more typical in real world. The proposed case stresses CSS processing, DOM and a little bit of painting. 

Regarding the real-world reflection, we’re inspired by a list of websites that put an image based carousel/slideshow along with list/table of contents as the UI pattern to organize and present their information. Some of the them are listed below.



| Real World Scenario  | URL | Typical UI Elements  | Typical Interactions | Typical Web tech exercised |
| ------------- | ------------- |------------- | ------------- |------------- |
| Netflix Top 10 TV  | https://top10.netflix.com/tv  | Carousel & Table of Popular contents | Change selection in Dropdown triggers the update of carousel images and contents in table | CSS transform, opacity/size settings |
| IMDB Index  | https://www.imdb.com/  | Carousel & List of contents in DIV blocks | Click the arrow button in carousel to update the list of the contents | CSS transform, opacity/color settings |
| Facebook photo  | https://www.facebook.com/photo/?fbid=742932955788401&set=a.636245978533785 | Slideshow & List of contents in DIV blocks | Click the arrow button in carousel to update the list of the contents | CSS opacity/color/padding settings |
| Walmart Complete the look | https://www.walmart.com/ip/The-Beatles-Men-s-Abbey-Road-Graphic-T-Shirt-with-Short-Sleeves/1786976753?athbdg=L1600 | Carousel & List of contents in DIV blocks | Click the arrow button in carousel to update the list of the contents in “View details” window | CSS fade-out animation, opacity/visibility settings |

**Comment by HongZheng** [comment]
I have updated the code according to the comments, please review code at  https://github.com/intel-staging/Speedometer/tree/rich_css/resources/tentative/search-in-featured-page
A live demo at https://hongzheng.github.io/sp3-rich_css/?suite=Search-In-Featured-Page#home

**Comment by rniwa** [comment]
Is there a PR to add this workload somewhere?

**Comment by HongZheng** [comment]
> Is there a PR to add this workload somewhere?

I have submitted a PR #247, please review.

**Comment by camillobruni** [comment]
I like the CSS heavy part of this workload, but I still have some doubts:
- A lot of time is spent in just building up a table (~ 25% of the time), maybe that's something to optimise
- Having animations in this workload seems a bit counter intuitive. In order to boost the score, the most straight-forward (and *wrong*) thing to do, would be to not do any animation (in the extreme case) to free up resources for the main-thread JS / DOM part.
- The CSS is rather small for a typical website (maybe you had plans to extend this?)

Maybe we can keep the CSS rules with animations in there, but don't trigger them.

**Comment by HongZheng** [comment]
As I said in PR #247, the generated table contains some heavy CSS effects and animations, which reflects the purpose of the workload. But current solution may introduce much HTML parsing overhead which we will optimise later.
As async step won’t be ready until SP4, the workload currently only measures the initial frame after the table is generated. So animations don't happen in the scoring region. The result is something like "keep the CSS rules with animations in there, but don't trigger them".

**Comment by rniwa** [comment]
I'm at a bit of loss as to what state this proposal is in. What is the proposed PR for Speedometer 3? Is it https://github.com/WebKit/Speedometer/pull/247 ?

If so, that workload seems to induce a bunch of stray async tasks that run outside of the measured time window both on Chrome & Safari so we should fix that.

More generally, while I appreciate & value your contributions, this workload seems to be more about measuring the page load speed than web app responsiveness. Since the goal of Speedometer is measuring web app responsiveness, not page load speed, this test might be out of scope by concept. If we were to include this test in Speedometer 3, the we need to put focus on app responsiveness after the page load had completed.

**Comment by camillobruni** [comment]
I share rniwa's sentinment here. Maybe let's not rush this and put investigation / development on pause for this workload (and maybe think about it again for the next version 4) until we have stabilised everything else.

**Comment by MayuraRam** [comment]
Thanks for your comments. rniwa - regarding your comment "measuring the page load speed than web app responsiveness" - The measured part of the workload occurs after the page is loaded. So it does measure page responsiveness, by measuring the time it takes to create the initial frame and not the page load speed.

**Comment by rniwa** [comment]
> Thanks for your comments. rniwa - regarding your comment "measuring the page load speed than web app responsiveness" - The measured part of the workload occurs after the page is loaded. So it does measure page responsiveness, by measuring the time it takes to create the initial frame and not the page load speed.

Measuring the initial frame still sounds like a page load test to me. I think we should not measure the initial frame / page load at all for this workload to be stay focused.
